name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create deployment directory
        run: |
          mkdir -p deploy
          # Copy web files
          cp -r index.html deploy/
          cp -r web deploy/
          # Create a copy of Python files with proper permissions
          mkdir -p deploy/devnagari_lang
          cp -r devnagari_lang/*.py deploy/devnagari_lang/
          chmod 644 deploy/devnagari_lang/*.py
          # Copy examples
          cp -r examples deploy/
          # Create a test file to verify deployment
          echo "Test file" > deploy/test.txt
          # List contents to verify
          ls -la deploy/devnagari_lang/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'deploy'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 